[package]
name = "math"
version = "0.1.1"
authors = ["Sebastian Köln <sebk@rynx.org>"]
build = "build.rs"

[dependencies]
rand = "*"
tuple = { features = ["impl_simd"], git="https://github.com/s3bk/tuple.git" }
num = "*"
simd = "*"
lalrpop-util = "*"
regex = "*"
fmath = { git = "https://github.com/s3bk/fmath.git" }
optimization = "*"
env_logger = "*"
typenum = "*"

[build-dependencies]
lalrpop = "*"

[dev-dependencies]
jack = "*"
hound = "*"
termion = "*"
